version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: "iman"
      POSTGRES_PASSWORD: "iman"
      POSTGRES_DB: "iman"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iman -d iman"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge