version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: "iman"
      POSTGRES_PASSWORD: "iman"
      POSTGRES_DB: "iman"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data